on:
  release:
    types:
      - published

name: release v1.x
jobs:
  v1_x:
    runs-on: ubuntu-latest
    if: github.actor == 'amazing-github-actions[bot]' && startsWith(github.event.release.tag_name, 'v1.')
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run package
      - uses: ./
        id: auth
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: set release bot
        run: |
          git config user.name ${GIT_COMMITTER_NAME}
          git config user.email ${GIT_COMMITTER_EMAIL}
        env:
          GIT_COMMITTER_NAME: ${{ secrets.RELEASE_APP_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.RELEASE_APP_EMAIL }}
      - run: |
          git add --force ./dist
          git commit -m "chore(release): ${SEMVER} [skip ci]"
        env:
          SEMVER: ${{ github.event.release.tag_name }}
      - run: 'git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:refs/heads/v1.x'
        env:
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
