on:
  push:
    branches:
      - main

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm run package
      - uses: ./
        id: auth
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: release, if needed
        run: npx semantic-release
        env:
          GIT_AUTHOR_NAME: ${{ secrets.RELEASE_APP_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.RELEASE_APP_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.RELEASE_APP_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.RELEASE_APP_EMAIL }}
          GITHUB_TOKEN: ${{ steps.auth.outputs.token }}
